version: "3"
services:
  rabbit_consumer:
    build: .
    restart: "no"
    image: stfc/rabbit-consumer:latest
    env_file:
      - .env
    environment:
      AQ_FQDN: $HOSTNAME
    volumes:
      - "/etc/krb5.conf:/etc/krb5.conf:ro"
      - "/etc/krb5.keytab:/etc/krb5.keytab:ro"
      - "/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro"
      - "./consumer.ini:/usr/src/app/consumer.ini:ro"
