# Entrypoint scripts
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-entrypoints
data:
{{ (.Files.Glob "include/consumer-entrypoint.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "include/kinit.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "include/sidecar-entrypoint.sh").AsConfig | indent 2 }}

# File configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kerberos-files
data:
{{ (.Files.Glob "include/krb5.conf").AsConfig | indent 2 }}

# Env configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  refreshInterval: "{{ .Values.kerberosSidecar.refreshInterval }}"
  principle: {{ .Values.kerberosSidecar.principle }}
