apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: rabbit-consumer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbit-consumer
  template:
    metadata:
      labels:
        app: rabbit-consumer
    spec:
      containers:
        - name: kerberos-sidecar
          image: "{{ .Values.kerberosSidecar.image.repository }}:{{ .Values.kerberosSidecar.image.tag }}"
          command: ["/bin/sh", "-c", "/etc/entrypoints.d/sidecar-entrypoint.sh"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: entrypoints
              mountPath: /etc/entrypoints.d
      volumes:
        - name: entrypoints
          configMap:
            name: {{ .Release.Name }}-entrypoints
            defaultMode: 0744
