apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: rabbit-consumer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbit-consumer
  template:
    metadata:
      annotations:
        # Force pod restart on configmap change
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        kubectl.kubernetes.io/default-container: consumer
      labels:
        app: rabbit-consumer
    spec:
      containers:
        - name: kerberos
          image: "{{ .Values.kerberosSidecar.image.repository }}:{{ .Values.kerberosSidecar.image.tag }}"
          command: ["/bin/sh", "-c", "/etc/entrypoints.d/sidecar-entrypoint.sh"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: entrypoints
              mountPath: /etc/entrypoints.d
            - name: krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: shared
              mountPath: /shared

        - name: consumer
          image: python:3.10
          command: ["/bin/sh", "-c", "/etc/entrypoints.d/consumer-entrypoint.sh"]
          volumeMounts:
            - name: entrypoints
              mountPath: /etc/entrypoints.d
            - name: shared
              mountPath: /shared
      
      volumes:
        - name: entrypoints
          configMap:
            name: {{ .Release.Name }}-entrypoints
            defaultMode: 0744
        - name: krb5-conf
          configMap:
            name: {{ .Release.Name }}-kerberos
        - name: shared
          emptyDir: {}
