name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install test runner and deps
        run: |
          python -m pip install --upgrade pip
          # Required for requests-kerberos
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install libkrb5-dev
          pip install -r OpenStack-Rabbit-Consumer/requirements.txt
          pip install -r OpenStack-Rabbit-Consumer/requirements-test.txt
      - name: Run OpenStack-Rabbit-Consumer tests
        run: pytest 
