name: Cloud Energy Collection Tests

on: [push, pull_request]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cloud-energy-collection/iriscasttools/requirements.txt

      - name: Run tests
        run: cd cloud-energy-collection/iriscasttools/ && python3 -m pytest .

      - name: Analyse with pylint
        run: |
          cd cloud-energy-collection/iriscasttools && pylint --recursive yes . test
