name: Rabbit Consumer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Required for requests-kerberos
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install libkrb5-dev
          pip install -r OpenStack-Rabbit-Consumer/requirements.txt
          pip install -r OpenStack-Rabbit-Consumer/requirements-test.txt
      - name: Run tests
        # Using Python3 to launch the module sets up the Python path for us
        run: cd OpenStack-Rabbit-Consumer && python3 -m pytest .
      - name: Analyse with pylint
        run: |
          cd OpenStack-Rabbit-Consumer && pylint --recursive yes rabbit_consumer test

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm lint OpenStack-Rabbit-Consumer/rabbit-consumer-chart --values OpenStack-Rabbit-Consumer/rabbit-consumer-chart/shared-values.yaml --values OpenStack-Rabbit-Consumer/rabbit-consumer-chart/dev-values.yaml --strict=true
